### ISSUE TITLE
安装mmcv问题

### ISSUE THREAD

**Issue by fang-lg** [WoojuLee24/OA-DG#2]
AssertionError: MMCV==1.7.2 is used but incompatible. Please install mmcv>=1.3.17, <=1.5.0.
使用教程安装会自动安装1.7.2的版本，但是这个版本太高了，换较低的版本又安装不上去

**Comment by ZhangYB-code** [comment]
我也遇到过同样的问题，现在已经解决。安装mmcv-full版本的，请到链接https://mmcv.readthedocs.io/zh-cn/v1.7.0/get_started/installation.html处使用pip安装，选择自己对应的pytorch和cuda版本，在选择mmcv-full==1.5.0，用它下面链接安装即可。

**Comment by fang-lg** [comment]
是我的cuda和torch太高了嘛？


这边最低只能安装1.6.0的，或者我可以直接把上述安装链接的版本改为mmcv-full==1.5.0嘛？




18103402方龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WoojuLee24/OA-DG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月7日(星期天) 下午5:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WoojuLee24/OA-DG] 安装mmcv问题 (Issue #2)





 
我也遇到过同样的问题，现在已经解决。安装mmcv-full版本的，请到链接https://mmcv.readthedocs.io/zh-cn/v1.7.0/get_started/installation.html处使用pip安装，选择自己对应的pytorch和cuda版本，在选择mmcv-full==1.5.0，用它下面链接安装即可。

**Comment by Lybnn** [comment]
可以直接把上述安装链接的版本改为mmcv-full==1.5.0，mmcv-full按需安装对应版本

**Comment by fang-lg** [comment]
> 可以直接把上述安装链接的版本改为mmcv-full==1.5.0，mmcv-full按需安装对应版本

大佬能加个联系方式探讨探讨吗？
