### ISSUE TITLE
Where is the object-aware augmentation step in the code?

### ISSUE THREAD

**Issue by zhangletian2** [WoojuLee24/OA-DG#7]
I appreciate your great work first!
Btw, I'm interested in the object-aware augmentation, can you point out where do you use it in the code?
Thanks a lot!

**Comment by WoojuLee24** [comment]
Thank you for your interest! Object-aware augmentation is in the `mmdet/datasets/pipelines/oa_mix.py`

**Comment by zhangletian2** [comment]
Thank you for the patient reply!
I follow the instructions and re-implement the experiment of **DWD** with torch2.0&cu118, but got significantly lower result:

Day Clear | Night Clear | Dusk Rainy | Night Rainy | Day Foggy
39.6 | 31.5 | 27.2 | 12.9 | 31.0

What could be wrong with the experiment?
Thanks!

**Comment by WoojuLee24** [comment]
The OA-DG and OA-Mix config files have not been uploaded yet. I have been busy with other commitments and finding it difficult to spare time. I plan to upload them within a month.

**Comment by WoojuLee24** [comment]
We have uploaded a OA-Mix config file of DWD.
