### ISSUE TITLE
A question about mAP in DWD datasets

### ISSUE THREAD

**Issue by Lybnn** [WoojuLee24/OA-DG#8]
Hello! author, when I was reproducing the code for this article, I followed the steps you provided and found that after training configs/OADG/dwd/faster_rcnn_r101_dc5_1x_dwd_oadg.py, the reproduction mAP was much lower than what you provided inside your paper. I think there is something wrong with one of my steps, after I checked your code it seems that OA-Mix and OA-Loss are not utilized, so what should I do to reach your mAP.
                       Daytime-sunny    Night-sunny   Dusk-rainy   Night-rainy     Daytime-foggy
OADG                55.8                          38.0                 33.9            16.8                    38.3
me                     52.5                         33.5                 29.0             13.9                   33.5

**Comment by WoojuLee24** [comment]
Thank you for your interest for our work. 
The OA-DG and OA-Mix config files have not been uploaded yet. The config files for DWD datasets are different from the config files for Cityscapes-C as the DWD dataset only covers four kinds of weather.
I have been busy with other commitments and finding it difficult to spare time. I plan to upload them within a month.

**Comment by Lybnn** [comment]
I see, thank you very much for your reply. I will keep following your work and look forward to being able to upload it soon. Thanks.
